
[DATA_NODE.WINE_PRODUCTION]
storage_type = "csv"
default_path = "data/wine_harvest_france_aoc_09_19.csv"
scope = "SCENARIO:SCOPE"

[TASK.ADD_WINE_COLORS]
inputs = [ "WINE_PRODUCTION:SECTION" ]
outputs = [ "WINE_PRODUCTION_WITH_COLORS:SECTION" ]
function = "config.functions.add_wine_colors:function"
skippable = "False:bool"

[DATA_NODE.WINE_PRODUCTION_WITH_COLORS]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[PIPELINE.PIPELINE_WINE]
tasks = [ "ADD_WINE_COLORS:SECTION" ]

[SCENARIO.SCENARIO_WINE]
pipelines = [ "PIPELINE_WINE:SECTION" ]
