


[TASK.TASK_TEST]
inputs = [ "DATA_NODE_TEST_INPUT:SECTION" ]
outputs = [ "DATA_NODE_TEST_OUTPUT:SECTION" ]
function = ""
skippable = "False:bool"

[DATA_NODE.DATA_NODE_TEST_OUTPUT]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"



[DATA_NODE.DATA_NODE_TEST_INPUT]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[SCENARIO.SCENARIO_TEST]
pipelines = [ "PIPELINE_TEST:SECTION" ]

[PIPELINE.PIPELINE_TEST]
tasks = [ "TASK_TEST:SECTION" ]
